---
branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
      releaseRules:
        - type: "feat"
          release: "minor"
        - type: "fix"
          release: "patch"
        - type: "chore"
          release: "patch"
        - type: "revert"
          release: "patch"
        - type: "ci"
          release: "patch"
        - type: "perf"
          release: "patch"
        - type: "refactor"
          release: "patch"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - type: feat
            section: Features
          - type: fix
            section: Bug Fixes
          - type: chore
            section: Routine Maintenance
          - type: revert
            section: Revert
          - type: ci
            section: Continuous Integration
          - type: perf
            section: Performance Improvements
          - type: refactor
            section: Code Refactoring
  - "@semantic-release/github"
